#+title: cardbrick

cardbrick is a mix of a famous card game and a famous brick game.

* Project setup

#+begin_example
npm install
#+end_example

** Compiles and hot-reloads for development

#+begin_example
npm run serve
#+end_example

** Compiles and minifies for production

#+begin_example
npm run build
#+end_example

** Runs tests

#+begin_example
npm run test
#+end_example

** Lints and fixes files

#+begin_example
npm run lint
#+end_example

* Copying

Copyright (C) 2019 Evgeny Pisemsky <evgeny@pisemsky.com>

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
